name: vector

on: [push, pull_request]

jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@master
    - name: Install and setup g++-10
      run: |
        sudo apt install gcc-10 g++-10
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 100 --slave /usr/bin/g++ g++ /usr/bin/g++-10 --slave /usr/bin/gcov gcov /usr/bin/gcov-10
    - name: Create build directory
      run: mkdir build
    - name: Compile code
      working-directory: build
      run: |
        cmake ..
        make
    - name: Run UTs
      working-directory: build
      run: |
        ctest -V
  Memory:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@master
    - name: Install and setup g++-10
      run: |
        sudo apt install gcc-10 g++-10
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 100 --slave /usr/bin/g++ g++ /usr/bin/g++-10 --slave /usr/bin/gcov gcov /usr/bin/gcov-10
    - name: Install valgrind
      run: sudo apt install valgrind
    - name: Create build directory
      run: mkdir build
    - name: Compile code
      working-directory: build
      run: |
        cmake ..
        make
    - name: Run Valgrind
      working-directory: build
      run: |
        valgrind --leak-check=full ./vector-ut
        valgrind --leak-check=full ./vector
